contao:
  localconfig:
    defaultSorting: 'dateAdded'
    statusTokenNewDisplayDuration: '+1 week'
    numberFormatDecimals: ','
    numberFormatThousands: '.'
    defaultNumberOfMainDetails: '3'
    defaultNumberOfMainAttr: '4'
    roomOptions: '1,2,3,4,5,6,7,8'
