estatemanager_api_read:
  path: /api/estatemanager/v{version}/{module}/{id}
  defaults:
    _controller: "Core:EstateManager:read"
    _scope: frontend
    _token_check: false
    id: null
  requirements:
    version: '\d+'
  methods: [GET]